In [21]:
#QUESTION 1
#as normal data
import pandas as pd
import scipy
import numpy

#Create outputfile
f = open("Question 1 Output.txt", "w")

hw02 = pd.read_csv('C:\PythonData\hwk01.csv', index_col=[0])

#reduce data set to C-F
hw02.drop(columns = ['A', 'B'], axis = 1, inplace = True)

#Standardize the data
from sklearn.preprocessing import StandardScaler

#Define the features
features = ['C', 'D', 'E', 'F']

#Seperate out the features
x = hw02.loc[:, features].values

#Standardize the feature values
x = StandardScaler().fit_transform(x)

#PCA Projection to 2D
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

principalComponents = pca.fit_transform(x)

principalDF = pd.DataFrame(data = principalComponents, columns = ['p1' , 'p2'])

f.write("QUESTION 1: PCA Values\n")
numpy.savetxt(f, principalDF, "%.4f")
f.close

principalDF.head()

         p1        p2
0  0.480950 -0.796346
1  1.748043  1.135319
2 -0.717156 -0.819107
3  0.469744 -1.143888
4  0.190048 -1.388727

In [60]:
#QUESTION 2.a.1
from scipy.spatial import distance
df = pd.read_csv('C:\PythonData\hwk01.csv', index_col=[0])
p = ('a1', 'b2', 515, -0.876, 6.4253, 45) #sample data (should prompt)
userDataArray = (p[2], p[3], p[4], p[5])
#print(userDataArray)

baseDst = 0
baseIdx = 0

#Create outputfile
g = open("Question 2.a.1 Output.txt", "w")

#Iterate through the Dataframe to find least dissimilar Euclidean distance
for index, row in df.iterrows():
    c = row['C'] 
    d = row['D']
    e = row['E']
    f = row['F']
    dfDataArray = (c, d, e, f)
    
    #Solve Base distance (first time only)
    if index == 0:
        baseDst = distance.euclidean(userDataArray, dfDataArray)
    
    #solve for Euclidean distance
    dst = distance.euclidean(userDataArray,dfDataArray)
    #check for current smallest distance (distance closest to zero)
    if dst < baseDst:
        #if smaller, this distance is new smallest distance
        baseDst = dst
        baseIdx = index
        #print(baseDst)
        #print(baseIdx)
#Write to text file    
writeFrame = df.loc[baseIdx : baseIdx]
g.write("QUESTION 2.a.1: Least Dissimilar Euclidean distance\n")
g.write(writeFrame.to_string())
g.close

#print results
print("In regards to Euclidean distance, the least dissimilar row found was at index #%d with value : %.4f" % (baseIdx, baseDst))
df.loc[baseIdx : baseIdx]

In regards to Euclidean distance, the least dissimilar row found was at index #529 with value : 34.2727

      A   B    C         D         E   F
529  a1  b2  518  2.093137  5.530146  11

In [43]:
#QUESTION 2.a.2
#Iterate through the Dataframe to find least dissimilar Manhattan distance

#Create outputfile
h = open("Question 2.a.2 Output.txt", "w")

for index2, row in df.iterrows():
    c = row['C'] 
    d = row['D']
    e = row['E']
    f = row['F']
    dfDataArray = (c, d, e, f)
    
    #Solve Base distance (first time only)
    if index2 == 0:
        baseDst = distance.cityblock(userDataArray, dfDataArray)
    
    #Solve for Manhattan distance
    dst = distance.cityblock(userDataArray, dfDataArray)
    #check for current smallest distance (distance closest to zero)
    if dst < baseDst:
        #if smaller, this distance is new smallest distance (save index)
        baseDst = dst
        baseIdx = index2
#Write to text file    
writeFrame = df.loc[baseIdx : baseIdx]
h.write("QUESTION 2.a.2: Least Dissimilar Manhattan distance\n")
h.write(writeFrame.to_string())
h.close        

#print results
print("In regards to Manhattan distance, the least dissimilar row found was at index #%d with value : %.4f" % (baseIdx, baseDst))
df.loc[baseIdx : baseIdx]

In regards to Manhattan distance, the least dissimilar row found was at index #529 with value : 40.8643

      A   B    C         D         E   F
529  a1  b2  518  2.093137  5.530146  11

In [45]:
#QUESTION 2.a.3
#Iterate through the Dataframe to find least dissimilar Chebyshev distance

#Create outputfile
j = open("Question 2.a.3 Output.txt", "w")

for index3, row in df.iterrows():
    c = row['C'] 
    d = row['D']
    e = row['E']
    f = row['F']
    dfDataArray = (c, d, e, f)
    
    #Solve Base distance (first time only)
    if index3 == 0:
        baseDst = distance.chebyshev(userDataArray, dfDataArray)
    
    #Solve for Manhattan distance
    dst = distance.chebyshev(userDataArray, dfDataArray)
    #check for current smallest distance (distance closest to zero)
    if dst < baseDst:
        #if smaller, this distance is new smallest distance (save index)
        baseDst = dst
        baseIdx = index3
        
#Write to text file    
writeFrame = df.loc[baseIdx : baseIdx]
j.write("QUESTION 2.a.3: Least Dissimilar Chebyshev distance\n")
j.write(writeFrame.to_string())
j.close   

#print results
print("In regards to Chebyshev distance, the least dissimilar row found was at index #%d with value : %.4f" % (baseIdx, baseDst))
df.loc[baseIdx : baseIdx]

In regards to Chebyshev distance, the least dissimilar row found was at index #529 with value : 34.0000

      A   B    C         D         E   F
529  a1  b2  518  2.093137  5.530146  11

In [59]:
#QUESTION 2.b
#Normalize user input
s = sum(userDataArray); 
userNorm = [float(i)/s for i in userDataArray]

#Create outputfile
k = open("Question 2.b Output.txt", "w")

#Iterate through the Dataframe to find least dissimilar Euclidean distance (NORMALIZED)
for index4, row in df.iterrows():
    c = row['C'] 
    d = row['D']
    e = row['E']
    f = row['F']
    dfDataArray = (c, d, e, f)
    #Normalize row
    s2 = sum(dfDataArray)
    dfNorm = [float(i)/s2 for i in dfDataArray]
    
    #Solve Base distance (first time only)
    if index4 == 0:
        baseDst = distance.euclidean(userNorm, dfNorm)
    
    #solve for Euclidean distance
    dst = distance.euclidean(userNorm,dfNorm)
    #check for current smallest distance (distance closest to zero)
    if dst < baseDst:
        #if smaller, this distance is new smallest distance
        baseDst = dst
        baseIdx = index4
        #print(baseDst)
        #print(baseIdx)
#Write to text file    
writeFrame = df.loc[baseIdx : baseIdx]
k.write("QUESTION 2.b: Least Dissimilar Euclidean distance (NORMALIZED)\n")
k.write(writeFrame.to_string())
k.close           

#print results
print("In regards to Euclidean distance, the least dissimilar row found (when normalized) was at index #%d with value : %.4f" % (baseIdx, baseDst))
df.loc[baseIdx : baseIdx]

In regards to Euclidean distance, the least dissimilar row found (when normalized) was at index #234 with value : 0.0497

      A   B    C         D        E  F
234  a1  b1  195 -0.613266  9.28117  9

In [58]:
#Question 3
from scipy.stats import chi2_contingency

#Create outputfile
l = open("Question 3 Output.txt", "w")

#Populate a contingency table using crosstab()
df2 = pd.read_csv('C:\PythonData\hwk01.csv', index_col=[0])
df2.drop(columns = ['C', 'D', 'E', 'F'], axis = 1, inplace = True) #don't need this
table = pd.crosstab(df2.A, df2.B, margins = True)

#Print the findings 
chi2, p, dof, expected = chi2_contingency(table.values)

#Write to text file    
writeFrame = pd.crosstab(df2.A, df2.B, margins = True)
l.write("QUESTION 3: \nPearson’s Chi-square Test\n")
l.write("Chi-square statistic %0.3f where the p_value is %0.3f \n" % (chi2, p))
l.write("Since the p value (rAB) is greater than 0, A and B are postively correlated.\n")
l.write(writeFrame.to_string())
l.close  

print ("Chi-square statistic %0.3f where the p_value is %0.3f" % (chi2, p))
print ("Since the p value (rAB) is greater than 0, A and B are postively correlated.")
pd.crosstab(df2.A, df2.B, margins = True)

Chi-square statistic 13.463 where the p_value is 0.036
Since the p value (rAB) is greater than 0, A and B are postively correlated.

B     b1   b2   All
A
a1   174  132   306
a2   170  151   321
a3   247  126   373
All  591  409  1000